"use server";
import { revalidatePath, updateTag } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { createSupabaseServerClient } from "@/lib/supabase/server";
const hex=/^#[0-9a-fA-F]{6}$/;
export async function saveAppearance(formData:FormData){const admin=await requireAdmin("appearance.manage");const parsed=z.object({primary:z.string().regex(hex),accent:z.string().regex(hex),logo:z.string().min(1),font:z.enum(["geist","system"]),publish:z.boolean()}).parse({...Object.fromEntries(formData.entries()),publish:formData.has("publish")});const value={primary:parsed.primary,accent:parsed.accent,logo:parsed.logo,font:parsed.font};const supabase=(await createSupabaseServerClient())!;const payload=parsed.publish?{value,draft_value:value,updated_by:admin.userId}:{draft_value:value,updated_by:admin.userId};const {error}=await supabase.from("store_settings").update(payload).eq("key","identity");if(error)throw new Error(error.message);await supabase.from("audit_logs").insert({actor_id:admin.userId,action:parsed.publish?"appearance.publish":"appearance.draft",entity_type:"store_settings",entity_id:"identity",new_data:value});if(parsed.publish)updateTag("store-settings");revalidatePath("/", "layout");revalidatePath("/admin/aparencia");}
export async function saveHomepageSection(formData:FormData){const admin=await requireAdmin("appearance.manage");const parsed=z.object({id:z.uuid(),title:z.string().max(120),sort_order:z.coerce.number().int().min(0),visible:z.boolean(),content:z.string().transform(v=>JSON.parse(v) as unknown)}).parse({...Object.fromEntries(formData.entries()),visible:formData.has("visible")});const supabase=(await createSupabaseServerClient())!;const {error}=await supabase.from("homepage_sections").update({title:parsed.title,sort_order:parsed.sort_order,visible:parsed.visible,draft_content:parsed.content}).eq("id",parsed.id);if(error)throw new Error(error.message);await supabase.from("audit_logs").insert({actor_id:admin.userId,action:"homepage_section.update",entity_type:"homepage_section",entity_id:parsed.id,new_data:parsed});revalidatePath("/admin/aparencia");}
export async function publishHomepage(){const admin=await requireAdmin("appearance.manage");const supabase=(await createSupabaseServerClient())!;const {data:sections}=await supabase.from("homepage_sections").select("id,draft_content");for(const section of sections??[]){if(section.draft_content)await supabase.from("homepage_sections").update({content:section.draft_content,published:true}).eq("id",section.id);}await supabase.from("audit_logs").insert({actor_id:admin.userId,action:"homepage.publish",entity_type:"homepage"});revalidatePath("/");revalidatePath("/admin/aparencia");}
