import type { Product } from "@/lib/types";

export const products: Product[] = [
  {
    id: "camisa-i-2025",
    slug: "camisa-i-tubaroes-2025",
    name: "Camisa I Tubarões 2025",
    shortDescription: "O manto oficial para levar a força dos Tubarões por onde você for.",
    description:
      "Camisa esportiva oficial da Atlética Tubarões UVV, com tecido leve, respirável e acabamento pensado para acompanhar jogos, treinos e o dia a dia no campus.",
    category: "Roupas",
    categorySlug: "roupas",
    image: "/products/camisa-i-2025.jpg",
    gallery: ["/products/camisa-i-2025.jpg"],
    price: 69.9,
    cost: 34,
    sku: "TUVV-CAM-I-25",
    stock: 18,
    minimumStock: 5,
    active: true,
    featured: true,
    isNew: true,
    bestSeller: true,
    options: [
      { name: "Tamanho", values: ["PP", "P", "M", "G", "GG", "XGG"], required: true },
    ],
    weightGrams: 280,
  },
  {
    id: "camiseta-cc-azul",
    slug: "camiseta-ciencia-da-computacao-azul",
    name: "Camiseta Ciência da Computação Azul",
    shortDescription: "Tecnologia, curso e atlética na mesma camiseta.",
    description:
      "Camiseta casual em malha confortável, criada para a galera de Ciência da Computação representar o curso com identidade.",
    category: "Roupas",
    categorySlug: "roupas",
    image: "/products/camiseta-cc-azul.jpg",
    gallery: ["/products/camiseta-cc-azul.jpg"],
    price: 54.9,
    cost: 26,
    sku: "TUVV-CC-AZ",
    stock: 26,
    minimumStock: 6,
    active: true,
    featured: true,
    isNew: false,
    options: [
      { name: "Tamanho", values: ["P", "M", "G", "GG"], required: true },
      { name: "Modelo", values: ["Tradicional", "Baby look"], required: true },
    ],
    weightGrams: 220,
  },
  {
    id: "copo-tubaroes",
    slug: "copo-tubaroes",
    name: "Copo Tubarões",
    shortDescription: "O copo da torcida, agora sempre com você.",
    description: "Copo personalizado da Atlética Tubarões UVV, resistente e ideal para os eventos da atlética.",
    category: "Acessórios",
    categorySlug: "acessorios",
    image: "/products/copo-tubaroes.jpg",
    gallery: ["/products/copo-tubaroes.jpg"],
    price: 10,
    compareAtPrice: 20,
    cost: 5,
    sku: "TUVV-COPO-01",
    stock: 42,
    minimumStock: 10,
    active: true,
    featured: true,
    isNew: false,
    bestSeller: true,
    options: [],
    weightGrams: 90,
  },
  {
    id: "tirante-rei-dos-mares",
    slug: "tirante-tubaroes-rei-dos-mares",
    name: "Tirante Rei dos Mares",
    shortDescription: "Seu crachá com a identidade do maior predador dos mares.",
    description: "Tirante estampado com mosquetão metálico, acabamento reforçado e arte oficial Tubarões UVV.",
    category: "Tirantes",
    categorySlug: "tirantes",
    image: "/products/tirante-rei-dos-mares.jpg",
    gallery: ["/products/tirante-rei-dos-mares.jpg"],
    price: 10,
    compareAtPrice: 15,
    cost: 4,
    sku: "TUVV-TIR-RM",
    stock: 35,
    minimumStock: 8,
    active: true,
    featured: true,
    isNew: false,
    options: [],
    weightGrams: 45,
  },
  {
    id: "tirante-invasao",
    slug: "tirante-tubaroes-invasao-a-praia",
    name: "Tirante Invasão à Praia",
    shortDescription: "Um clássico para identificar quem fecha com a atlética.",
    description: "Tirante de poliéster com impressão de alta definição e mosquetão metálico.",
    category: "Tirantes",
    categorySlug: "tirantes",
    image: "/products/tirante-invasao.jpg",
    gallery: ["/products/tirante-invasao.jpg"],
    price: 10,
    compareAtPrice: 15,
    cost: 4,
    sku: "TUVV-TIR-IP",
    stock: 28,
    minimumStock: 8,
    active: true,
    featured: false,
    isNew: false,
    options: [],
    weightGrams: 45,
  },
  {
    id: "tirante-grande",
    slug: "tirante-grande-tubaroes",
    name: "Tirante Grande Tubarões",
    shortDescription: "Mais presença e conforto para o seu dia no campus.",
    description: "Tirante largo, resistente e confortável, com estampa Tubarões UVV.",
    category: "Tirantes",
    categorySlug: "tirantes",
    image: "/products/tirante-grande.jpg",
    gallery: ["/products/tirante-grande.jpg"],
    price: 10,
    compareAtPrice: 15,
    cost: 4.5,
    sku: "TUVV-TIR-GR",
    stock: 31,
    minimumStock: 8,
    active: true,
    featured: false,
    isNew: false,
    options: [],
    weightGrams: 55,
  },
  {
    id: "baby-look-branca",
    slug: "camisa-baby-look-shark-branca",
    name: "Baby look Shark Branca",
    shortDescription: "Modelagem ajustada e visual leve para representar a Tubarões.",
    description: "Baby look em algodão macio, com estampa frontal e modelagem confortável.",
    category: "Roupas",
    categorySlug: "roupas",
    image: "/products/baby-look-branca.jpg",
    gallery: ["/products/baby-look-branca.jpg"],
    price: 49.9,
    cost: 24,
    sku: "TUVV-BL-BR",
    stock: 12,
    minimumStock: 5,
    active: true,
    featured: false,
    isNew: true,
    options: [{ name: "Tamanho", values: ["PP", "P", "M", "G", "GG"], required: true }],
    weightGrams: 200,
  },
  {
    id: "camisa-si-preta",
    slug: "camisa-sistemas-de-informacao-preta",
    name: "Camisa Sistemas de Informação Preta",
    shortDescription: "A camisa de quem transforma informação em impacto.",
    description: "Camiseta universitária em algodão, acabamento premium e estampa do curso.",
    category: "Roupas",
    categorySlug: "roupas",
    image: "/products/camisa-si-preta.jpg",
    gallery: ["/products/camisa-si-preta.jpg"],
    price: 54.9,
    cost: 26,
    sku: "TUVV-SI-PT",
    stock: 15,
    minimumStock: 5,
    active: true,
    featured: false,
    isNew: false,
    options: [{ name: "Tamanho", values: ["P", "M", "G", "GG"], required: true }],
    weightGrams: 220,
  },
  {
    id: "camisa-cc-preta",
    slug: "camisa-ciencia-da-computacao-preta",
    name: "Camisa Ciência da Computação Preta",
    shortDescription: "Código, café e Tubarões.",
    description: "Camiseta preta do curso de Ciência da Computação, em malha confortável e resistente.",
    category: "Roupas",
    categorySlug: "roupas",
    image: "/products/camisa-cc-preta.jpg",
    gallery: ["/products/camisa-cc-preta.jpg"],
    price: 54.9,
    cost: 26,
    sku: "TUVV-CC-PT",
    stock: 8,
    minimumStock: 5,
    active: true,
    featured: false,
    isNew: false,
    options: [{ name: "Tamanho", values: ["P", "M", "G", "GG"], required: true }],
    weightGrams: 220,
  },
];

export const categories = [
  { name: "Roupas", slug: "roupas", description: "Vista a força da nossa atlética.", image: "/products/camisa-i-2025.jpg" },
  { name: "Acessórios", slug: "acessorios", description: "Tubarões em todos os detalhes.", image: "/products/copo-tubaroes.jpg" },
  { name: "Tirantes", slug: "tirantes", description: "Seu curso e sua atlética com você.", image: "/products/tirante-rei-dos-mares.jpg" },
] as const;

export const courses = [
  "Ciência da Computação",
  "Sistemas de Informação",
  "Engenharia de Software",
  "Análise de Sistemas",
] as const;

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug && product.active);
}

export function getProductById(id: string) {
  return products.find((product) => product.id === id && product.active);
}

